version: '3'
services:
  api:
    image: node:18
    container_name: progfolio_api
    ports:
     - 3000:3000
    
    volumes:
     - type: bind
       source: ./
       target: /code
    working_dir: /code

    command: bash -c "npm install && npm run dev"
