version: '3'
services:
  api:
    image: node:18
    container_name: progfolio_api
    ports:
      - 3000:3000
    networks:
      - backend_network
    volumes:
      - type: bind
        source: ./
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"

networks:
  backend_network:
